{{- if (eq .Values.global.secrets.aws.enable true) }}
{{- if (eq .Values.global.secrets.aws.use_iam_role false) }}
apiVersion: v1
data:
  key: {{ .Values.global.secrets.aws.AWS_ACCESS_KEY_ID | b64enc }}
  secret: {{ .Values.global.secrets.aws.AWS_SECRET_ACCESS_KEY | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
{{- end }}
