{{- if .Values.apmConnectAutoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.fullname" . }}-apm-connect
  namespace: {{ .Release.Namespace }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "autoscaling.apmConnectAutoscaling.fullname" . }}
  minReplicas: {{ .Values.apmConnectAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.apmConnectAutoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: es_connect_heap_utilization_pcnt
      targetAverageValue: "{{ .Values.apmConnectAutoscaling.memory.targetPCNT }}"
  - type: Pods
    pods:
      metricName: es_connect_nio_utilization_pcnt
      targetAverageValue: "{{ .Values.apmConnectAutoscaling.memory.targetPCNT }}"
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: "{{ .Values.apmConnectAutoscaling.cpu.targetAverageValue }}"
{{- end -}}
