{{- if and .Values.archivalConnectAutoscaling.enabled .Values.global.archival.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoscaling.fullname" . }}-archival-connect
  namespace: {{ .Release.Namespace }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "autoscaling.archivalConnectAutoscaling.fullname" . }}
  minReplicas: {{ .Values.archivalConnectAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.archivalConnectAutoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: arch_connect_memory_usage_MiB
      targetAverageValue: "{{ .Values.archivalConnectAutoscaling.memory.targetAverageValue }}"
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: "{{ .Values.archivalConnectAutoscaling.cpu.targetAverageValue }}"
{{- end -}}
