apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}-petclinic-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appName" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectName" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: petclinic
data:
  application-mysql.properties: |
      spring.datasource.initialization-mode=always
      spring.profiles.active=mysql
      spring.datasource.url=jdbc:mysql://{{ template "mysql.fullname" . }}/petclinic
      spring.datasource.username={{ .Values.mysql.mysqlUser }}
      spring.datasource.password={{ .Values.mysql.mysqlPassword }}
