{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spring.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "spring.name" . }}
    chart: {{ template "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
    snappyflow/component: petclinic
{{- end -}}
