# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: snappyflowml/dataset-controller
  tag: 7
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serverPort: ":5001"

rawDataCleanupDays: 2

service:
  servicePort: 5001

ingest-controller:
  service:
    servicePort: 5000

billing-service:
  enabled: false
  url: 127.0.0.1:8000/api/v1/records/
  scheme: https

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  datasetcontroller:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
