# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

  postgresql:
    host: ""
    postgresqlDatabase: new_archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  secrets:
    gcs:
      enable: false
      secret: XX
      key: XX.json
    aws:
      enable: true
      AWS_DEFAULT_REGION: us-west-2
      AWS_ACCESS_KEY_ID: XXXX
      AWS_SECRET_ACCESS_KEY: XXXX

  kafkaBrokers: ""

  snappyflowDatapath:
    enabled: true
    releaseName: sf-datapath

  hive:
    userName: ubuntu
    host: 127.0.0.1
    port: 10000
    auth: NONE

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: ""
  snappyflowAppName: ""

  imagePullSecrets:
  - name: xxxx

image:
  repository: snappyflowml/dataset-controller
  tag: dev-10
  pullPolicy: IfNotPresent

uncompactedCleanUpImage:
  repository: snappyflowml/uncompacted-cleanup
  tag: dev-11

nameOverride: ""
fullnameOverride: ""

serverPort: ":5001"

cleanupInterval: 1
rawDataCleanupDays: 7
rawDataExpirationDays: 7

service:
  servicePort: 5001

ingest-controller:
  service:
    servicePort: 5000

billing-service:
  url: 34.209.150.189:8000/api/v1/records
  scheme: https

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  datasetcontroller:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
  uncompactedcleanup:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
