# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: snappyflowml/dataset-controller
  tag: 6
  pullPolicy: IfNotPresent

uncompactedCleanUpImage:
  repository: snappyflowml/uncompacted-cleanup
  tag: 6

nameOverride: ""
fullnameOverride: ""

serverPort: ":5001"

cleanupInterval: 1
rawDataCleanupDays: 7
rawDataExpirationDays: 7

service:
  servicePort: 5001

ingest-controller:
  service:
    servicePort: 5000

billing-service:
  url: 34.209.150.189:8000/api/v1/records
  scheme: https

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  datasetcontroller:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi
  uncompactedcleanup:
    limits:
      cpu: 10m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 10Mi
