{{- if .Values.jmeter.logger.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spring.fullname" . }}-jmeter-logger-conf
  labels:
    app: {{ template "spring.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    snappyflow/appname: {{ default .Release.Name .Values.global.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: jmeter
data:
{{ (.Files.Glob "logger_config_jmeter/*").AsConfig | indent 2 }}
{{- end }}

