{{- if and .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring.fullname" . }}-nginx
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    snappyflow/prometheus: {{ default "false" .Values.nginx.metrics.enabled | quote }}
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name={{ .Values.elb.name }},Stack={{ .Values.elb.stack }},snappyflow/appname={{ .Values.global.sfappname }},snappyflow/projectname={{ .Values.global.sfprojectname }}
  labels:
    app: {{ template "spring.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    snappyflow/appname: {{ default .Release.Name .Values.global.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: http
{{- if .Values.nginx.metrics.enabled }}
  - name: metrics
    port: 9113
    targetPort: nginx-exporter
{{- end }}
  selector:
    app: {{ template "spring.name" . }}
    release: {{ .Release.Name | quote }}
    snappyflow/component: nginx
{{- end }}
