{{- if .Values.mysql.aws.enabled }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ include "spring.fullname" . }}-rds
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: mysql
spec:
  clusterServiceClassExternalName: rdsmysql
  clusterServicePlanExternalName: custom
  parameters:
    AccessCidr: "0.0.0.0/0"
    MasterUsername: {{ .Values.mysql.mysqlUser }}
    AllocatedStorageAndIops: 100GB 1000IOPS
    # AllowMajorVersionUpgrade: false # OPTIONAL
    # AutoMinorVersionUpgrade: true # OPTIONAL
    # AvailabilityZones: Auto
    BackupRetentionPeriod: 0 # OPTIONAL
    # CidrBlocks: Auto # OPTIONAL
    # CopyTagsToSnapshot: true # OPTIONAL
    DBInstanceClass: db.t2.micro # OPTIONAL
    DBName: {{ .Values.mysql.mysqlDatabase }} # OPTIONAL
    EngineVersion: 5.7.17 # OPTIONAL
    MasterUserPassword: {{ .Values.mysql.mysqlPassword }} # OPTIONAL
    # MonitoringInterval: 1 # OPTIONAL
    MultiAZ: false # OPTIONAL
    # MysqlServerTimezone: UTC # OPTIONAL
    # NumberOfAvailabilityZones: 2 # OPTIONAL
    # CidrSize: 27 # OPTIONAL
    PortNumber: 3306         #{{ .Values.mysql.port }} # OPTIONAL
    # PreferredBackupWindow: 00:00-02:00 # OPTIONAL
    # PreferredMaintenanceWindowDay: Mon # OPTIONAL
    # PreferredMaintenanceWindowEndTime: 06:00 # OPTIONAL
    # PreferredMaintenanceWindowStartTime: 04:00 # OPTIONAL
    PubliclyAccessible: true # OPTIONAL
    StorageEncrypted: false # OPTIONAL
    # StorageType: io1 # OPTIONAL

{{- end }}