# Default values for discovery-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: snappyflowml/petclinic
  tag: latest
  pullPolicy: IfNotPresent

# Global application tags   
# sfappname key will be replaced with snappyflow/appaname and
# sfprojectname key replaced with snappyflow/projectname during helm chart deployment
# sfappname: petclinic --> snappyflow/appname: petclinic
# sfprojectname: spring --> snappyflow/projectname: spring
global:
  sfappname: my-petclinic
  sfprojectname: my-project
  sfappname_key: snappyflow/appname
  sfprojectname_key: snappyflow/projectname

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  # name: ~

rbac:
  create: true

podAnnotations: {}
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "/actuator/prometheus"

spring:
  profile: mysql

jmx_exporter:
  enabled: true
  image:
    repository: bitnami/jmx-exporter
    tag: latest
    pullPolicy: IfNotPresent
  port: 5556

## The list of ports that your app listens on
containerPort: 8080

extraEnv: {}

securityContext: {}
  # runAsUser: 1000
  # fsGroup: 1000

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

## uncomment and modify the following livenessProbe and readinessProbe.
## These defaults should work with anything that uses the spring health actuator.
livenessProbe: {}
#   httpGet:
#     path: /actuator/health
#     port: http
#   initialDelaySeconds: 300
#   periodSeconds: 10
readinessProbe: {}
#   httpGet:
#     path: /actuator/health
#     port: http
#   initialDelaySeconds: 60
#   periodSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  headless: true
  httpPort: 80
  ## If service.type is not set to NodePort, the following statement
  ## will be ignored.
  ##
  # nodePort: 32015

  ## Service type can be set to ClusterIP, NodePort or LoadBalancer.
  ##
  type: ClusterIP

  ## Service annotations
  ##
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  #   external-dns.alpha.kubernetes.io/hostname: drone.domain.tld.

ingress:
  ## If true, Ingress will be created.
  ##
  enabled: false

  ## Ingress annotations
  ##
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: 'true'

  ## hostnames must be provided if Ingress is enabled
  ##
  # hosts:
  #   - "*"

  ## Ingress TLS configuration secrets
  ## Must be manually created in the namespace
  ##
  # tls:
  #   - secretName: spring-tls
  #     hosts:
  #       - spring.example.io

podDisruptionBudget:
  enabled: false
  minAvailable: 1

mysql:
  logger:
    enabled: false
  mysql_exporter:
    enabled: true
  mysqlRootPassword: spring
  mysqlUser: spring
  mysqlPassword: spring
  mysqlDatabase: petclinic
  persistence:
    enabled: false
  logrotate:
    enabled: true
    env:
      LOGROTATE_COMPRESSION: compress
      # LOGROTATE_INTERVAL: hourly
      LOGROTATE_COPIES: 3
      LOGROTATE_SIZE: 5M
      LOGROTATE_DELAYCOMPRESS: false
      LOG_FILE_ENDINGS: "log jtl"
      LOGROTATE_LOGFILE: "/dev/stdout"
      LOGROTATE_PARAMETERS: "vf"
      LOG_FILE: "/dev/stdout"

