# Default values for Log Archival.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  namenode:
    repository: snappyflowml/hadoop-2.10.1
    pullPolicy: IfNotPresent
    tag: namenode
  datanode:
    repository: snappyflowml/hadoop-2.10.1
    pullPolicy: IfNotPresent
    tag: datanode
  hiveServer:
    repository: snappyflowml/hive-2.3.8-and-hadoop-2.10.1
    pullPolicy: IfNotPresent
    tag: server
  hiveMetastore:
    repository: snappyflowml/hive-2.3.8-and-hadoop-2.10.1
    pullPolicy: IfNotPresent
    tag: metastore

nameOverride: ""
fullnameOverride: ""

podAnnotations:
  prometheus.io/scrape: "false"

service:
  namenode:
    port: 8020
  datanode:
    port: 50010
  hiveServer:
    port: 10000
  hiveMetastore:
    port: 9083
    externalPort: 32500

containerResources:
  namenode:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  datanode:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  hiveServer:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  hiveMetastore:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
