{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "es-kafka-connect.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "es-kafka-connect.name" . }}
    chart: {{ template "es-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-connect-prometheus.yml: |+
    startDelaySeconds: 90
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
    - "java.lang:*"
    - "java.nio:*"
    - "kafka.connect:*"
    rules:
    - pattern: "kafka.connect<type=connect-worker-metrics>"
      cache: true
    - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
      cache: true
    - pattern: "kafka.connect<type=connect-worker-metrics, connector=([^:]+)>([^:]+):"
      cache: true
    - pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      cache: true
    - pattern: "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>([^:]+)"
      cache: true
    - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)
      cache: true
    - pattern: kafka.connect<type=connector-metrics, connector=(.+)><>([a-z-]+)
      cache: true
    - pattern: kafka.connect<type=(.+)-metrics, connector=(.+), task=(.+)><>(.+-total|.+-count|.+-ms|.+-ratio|.+-avg|.+-failures|.+-requests|.+-timestamp|.+-logged|.+-errors|.+-retries|.+-skipped|.+-rate|.+-max)
      cache: true
    - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
      name: java_lang_$1_$4_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><(.+)>(\w+)
      name: java_lang_$2_$4_$3_$1
      cache: true
    - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
      name: java_lang_$1_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><>(\w+)
      name: java_lang_$2_$3_$1
      cache: true
    - pattern: java.lang<type=(.*)>
      cache: true
    - pattern: java.nio<type=(.+), name=(.+)><>(\w+)
      name: java_nio_$1_$3_$2
      cache: true
{{- end }}

