apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}-headless
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
spec:
  ports:
  - port: {{ .Values.serverPort }}
    name: server
  - port: {{ .Values.leaderElectionPort }}
    name: leader-election
  clusterIP: None
  selector:
    app: {{ include "zookeeper.name" . | quote }}
    release: {{ .Release.Name | quote }}
