apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-ui-sfagent
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: ui
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    metrics:
      plugins:
      - name: kube-sfagent-nginx
        enabled: true
        interval: 300
        config:
          location: status
          {{- if .Values.sfapmui.tls.enabled }}
          port: 443
          secure: true
          {{- else }}
          port: 80
          secure: true
          {{- end }}
    logging:
      plugins:
      - name: nginx-access
        enabled: true
        config:
          log_path: "/var/log/nginx/access.log"
          geo_info: {{ .Values.global.nginx_geo_info_collection}}
          ua_parser: {{ .Values.global.nginx_ua_parsing}}
      - name: nginx-error
        enabled: true
        config:
          log_path: "/var/log/nginx/error.log"
