{{- if .Values.logger.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-logger-conf
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
    snappyflow/component: mysql
data:
{{ (.Files.Glob "logger_config/*").AsConfig | indent 2 }}
{{- end }}
