global:
  hive:
    internal:
      enabled: false
    external:
      enabled: true
      # Below fields must be changed when external hive.external.enabled is true
      userName: ubuntu
      host: 127.0.0.1
      port: 10000
      auth: NONE
