apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: exporter
    snappyflow/plugin: kafka-jmx
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
  annotations:
    snappyflow/prometheus: 'true'
spec:
  ports:
  - name: broker
    port: 9092
{{- if and .Values.prometheus.jmx.enabled }}
  - name: jmx-exporter
    protocol: TCP
    port: {{ .Values.jmx.port }}
    targetPort: {{ .Values.prometheus.jmx.port }}
{{- end }}
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}
---
{{- if and .Values.prometheus.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-exporter
  labels:
    app: {{ include "kafka.name" . }}-exporter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: exporter
    snappyflow/plugin: kafka
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
  annotations:
    snappyflow/prometheus: 'true'
spec:
  ports:
  - name: kafka-exporter
    protocol: TCP
    port: {{ .Values.prometheus.kafka.port }}
    targetPort: {{ .Values.prometheus.kafka.port }}
  selector:
    app: {{ include "kafka.name" . }}-exporter
    release: {{ .Release.Name }}
{{- end }}
