apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    snappyflow/appname: {{ default .Release.Name .Values.global.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.global.sfprojectname }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: broker
    port: 9092
  clusterIP: None
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}
