kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-system-migration-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "ingest-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "hive": {
        "userName": "{{ template "ingest-controller.hive-server.username" . }}",
        "host": "{{ template "ingest-controller.hive-server.host" . }}",
        "port": {{ template "ingest-controller.hive-server.port" . }},
        "auth": "{{ template "ingest-controller.hive-server.auth" . }}"
      }
    }
