apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-priority-class
value: {{ .Values.priority }}
preemptionPolicy: Never
globalDefault: false
description: "This priority class is used by sf-archival components: ingest/dataset/compaction controllers"
