apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expressCart.fullname" . }}-scripts
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "expressCart.name" . }}
    chart: {{ include "expressCart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
    snappyflow/component: mysql
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
