{{- if .Values.jmeter.logger.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "expressCart.fullname" . }}-jmeter-logger-conf
  labels:
    app: {{ template "expressCart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{ default "snappyflow/appName" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectName" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
data:
{{ (.Files.Glob "logger_config_jmeter/*").AsConfig | indent 2 }}
{{- end }}

