apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "expressCart.fullname" . }}
  labels:
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
{{ include "expressCart.labels" . | indent 4 }}
  {{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "expressCart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
      {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "expressCart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      {{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "expressCart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-db
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', until nc -z -w 2 {{ .Release.Name }}-mongodb 27017 && echo mongodb ok;do sleep 2;done]
      - name: init-db
        image: mahendra0939/expresslog:v1
        imagePullPolicy: IfNotPresent
        command: ['npm','run','testdata']
        volumeMounts:
          - name: config
            mountPath: /var/expressCart/config/settings.json
            subPath: settings.json
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NODE_ENV 
            value: "production"
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_PORT
            value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /var/expressCart/config/settings.json
              subPath: settings.json
      volumes:
        - name: config
          configMap:
            name: {{ include "expressCart.fullname" . }}-expresscart-config  
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
