{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "expressCart.serviceAccountName" . }}
  labels:
    snappyflow/appname: {{ default .Release.Name .Values.sfappname }}
    snappyflow/projectname: {{ default .Release.Name .Values.sfprojectname }}
{{ include "expressCart.labels" . | indent 4 }}
{{- end -}}
