apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-gp2
  annotations:
    "helm.sh/hook": pre-install
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
