{{- if .Values.tomcatplugin.sfagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfagent-tomcat-{{ .Release.Name }}
  labels:
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: tomcat
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    metrics:
      plugins:
      - name: tomcat
        enabled: true
        interval: 300
        config:
          proxy: false
          port: 8080
          protocol: http
          username: admin
          password: admin@12345
          documentsTypes:
                - tomcatStats
                - requestProcessorStats
                - jvmStats
                - contextStats
    logging:
      plugins:
      - name: tomcat-access
        enabled: true
        config:
          log_path: "/opt/bitnami/tomcat/logs/localhost_access*.txt"
{{- end }}
