apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-create-compaction-candidates
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "compaction-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "compaction-controller.fullname" . }}; do echo waiting for {{ include "compaction-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "compaction-controller.fullname" . }}/compaction/create
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-queue-compaction-candidates
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "compaction-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "compaction-controller.fullname" . }}; do echo waiting for {{ include "compaction-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "compaction-controller.fullname" . }}/compaction/queue
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-run-compaction
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "compaction-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup {{ include "compaction-controller.fullname" . }}; do echo waiting for {{ include "compaction-controller.fullname" . }}; sleep 5; done"]
          containers:
          - name: main
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST http://{{ include "compaction-controller.fullname" . }}/compaction/start
          restartPolicy: Never
