apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- if .Values.postgresql.enabled }}
  db_host: {{ .Release.Name }}-postgresql
  db_port: "5432"
  db_password: {{ .Values.postgresql.multidbUserPassord }}
  db_username: {{ .Values.postgresql.multidbUser }}
  {{- else }}
  db_host: "{{ .Values.postgresql.external.db_host }}"
  db_port: "{{ .Values.postgresql.external.db_port }}"
  db_password: "{{ .Values.postgresql.external.db_password }}"
  db_username: "{{ .Values.postgresql.external.db_username }}"
  {{- end }}
  keycloak_password: "{{ .Values.keycloak.keycloak_password }}"
  keycloak_username: "{{ .Values.keycloak.keycloak_username }}"