apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
#{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: db-ready
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until pg_isready -d postgres://${db_user}:${db_password}@${db_host}:${db_port}/${db_name}; do sleep 3; done"
          {{- if .Values.postgresql.enabled }}
          env:
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.keycloak.tls.enabled }}
          ports:
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
          volumeMounts:
          - name: certs
            mountPath: /etc/x509/https
            readOnly: true
          {{- else }}
            ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.keycloak.tls.enabled }}          
          - name: X509_CA_BUNDLE
            value: /etc/x509/https/tls.crt /etc/x509/https/tls.key
          {{- end }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key:  db_username
                name: {{ .Release.Name }}-config
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key:  db_password
                name: {{ .Release.Name }}-config
          - name: DB_ADDR
            valueFrom:
              secretKeyRef:
                key:  db_host
                name: {{ .Release.Name }}-config
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key:  db_port
                name: {{ .Release.Name }}-config
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                key:  db_name
                name: {{ .Release.Name }}-config
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: DB_VENDOR
            value: "postgres"
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                key:  keycloak_username
                name: {{ .Release.Name }}-config
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                key:  keycloak_password
                name: {{ .Release.Name }}-config
      {{- if .Values.keycloak.tls.enabled }}  
      volumes:
        - name: certs
          secret:
            secretName: {{ .Release.Name }}-tls
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
