apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.keycloak.tls.enabled }} 
    - port: 8443
      targetPort: 8443
      name: https
    {{- else }} 
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
    {{- end }} 
    
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
