{{- if .Values.keycloak.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.keycloak.certskey }}
  tls.crt: {{ .Values.keycloak.certscrt }}
{{- end }}
