apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfnginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sfnginx.name" . }}
    helm.sh/chart: {{ include "sfnginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  snappyflow.conf: |
    upstream elasticsearch {
        server {{ .Values.config.es1 }}:9200;
        server {{ .Values.config.es2 }}:9200;
        server {{ .Values.config.es3 }}:9200;
    }
    client_max_body_size 10M;
    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;


         listen 9200;
         location / {
             proxy_pass http://elasticsearch;
        }
        
        location /status {
            stub_status;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

    

