# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
dataset-controller-cron:
  intervalInSec: 1800
  path: "/datasets/uncompact/refresh"
  dataset-controller:
    service:
      servicePort: 80

compaction-controller-create-cron:
  intervalInSec: 600
  path: "/compaction/create"
  compaction-controller:
    service:
      servicePort: 80

compaction-controller-queue-cron:
  intervalInSec: 600
  path: "/compaction/queue"
  compaction-controller:
    service:
      servicePort: 80

compaction-controller-start-cron:
  intervalInSec: 120
  path: "/compaction/start"
  compaction-controller:
    service:
      servicePort: 80

ingest-controller-sink-cron:
  intervalInSec: 300
  path: "/ingest/datasets/monitor/sink"
  ingest-controller:
    service:
      servicePort: 80

dataset-controller-billing-cron:
  intervalInSec: 3600
  path: "/datasets/profile/billing"
  dataset-controller:
    service:
      servicePort: 80

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  cron:
    limits:
      cpu: 25m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 25Mi
