kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "log-archival.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "log-archival.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "serverPort": "{{ .Values.serverPort }}",
      "datasetURL": "http://{{ template "log-archival.dataset-controller.fullname" . }}",
      "ingestURL": "http://{{ template "log-archival.ingest-controller.fullname" . }}",
      "kafkaBrokers": "{{ .Values.global.kafkaBrokers }}",
      "kafkaRestURL": "http://{{ template "log-archival.kafkaRest.fullname" . }}:8082",
      "kafkaRestAuth": "http://{{ template "log-archival.authenticator.fullname" . }}"
    }
