apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sfagent-config
data:
  config.yaml: |-
    key: "{{ .Values.global.key }}"
    metrics:
        plugins:
        - name: redisdb
          enabled: true
          interval: 10
          config:
            port: 6379
            host: localhost
            user: db_user
            password: P@s$w0rd123!
            documentsTypes: []
