apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
  clusterconfig.yaml: |
{{ toYaml .Values.cluster_agent.configmap | indent 4 }}
  nodeconfig.yaml: |
{{ toYaml .Values.node_agent.kubelet_configmap | indent 4 }}
  promconfig.yaml: |
{{ toYaml .Values.node_agent.prometheus_configmap | indent 4 }}
  interval.yaml: |
{{ toYaml .Values.node_agent.plugin_interval | indent 4 }}