apiVersion: v2
name: sfapm
description: A Helm chart to deploy snappyflow on Kubernetes
home: http://www.snappyflow.io
type: application
version: 0.1.1
appVersion: 1.0.0

dependencies:
- name: redis
  version: 10.7.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version:  8.10.5
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
