{{- if and .Values.schemaGenerator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}-schema-generator-configmap
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |+
    intervalInMin: {{ .Values.schemaGenerator.intervalInMin }}
    db:
      name:  "{{ .Values.global.postgresql.postgresqlDatabase }}"
      user:  "{{ .Values.global.postgresql.postgresqlUsername }}"
      password: "{{ .Values.global.postgresql.postgresqlPassword }}"
      host: {{ .Values.global.postgresql.host }}
      port: {{ .Values.global.postgresql.servicePort }}
    targets:
{{ toYaml .Values.schemaGenerator.targets | indent 4 }}
      url: "http://localhost:{{ .Values.servicePort }}"
{{- end }}
