apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-apm
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: server
data:
    {{- if .Values.postgresql.enabled }}
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "snappyflow"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    {{- else }}
    DB_HOST: {{ .Values.postgresql.external.dbHost }}
    DB_PORT: {{ .Values.postgresql.external.dbPort | default "5432"  | quote }}
    DB_NAME: "snappyflow"
    DB_USER: {{ .Values.postgresql.external.dbUser }}
    DB_PASSWORD: {{ .Values.postgresql.external.dbPassword }}
    {{- end }}
    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"
    VIZBUILDER_HOST: {{ include "sfapm.fullname" . }}-vizbuilder
    VIZBUILDER_PORT: "{{ .Values.vizbuilder.service.port }}"
    {{- if .Values.keycloak.enabled }}
    KEYCLOAK_MODE: "True"
    KEYCLOAK_SERVER: "{{ .Values.keycloak.serverIP }}"
    KEYCLOAK_USER: "{{ .Values.keycloak.user }}"
    KEYCLOAK_PASSWORD: "{{ .Values.keycloak.password }}"
    KEYCLOAK_REALM: "{{ .Values.keycloak.realm }}"
    KEYCLOAK_CLIENTID: "{{ .Values.keycloak.clientid }}"
    KEYCLOAK_CLIENTKEY: "{{ .Values.keycloak.clientkey }}"
    KEYCLOAK_PUBLICKEY: "{{ .Values.keycloak.publickey }}"
    SUPPORT_EMAIL: "{{ .Values.keycloak.supportemail }}"
    WEBSITE_URL: "{{ .Values.keycloak.websiteurl }}"
    DEFAULT_PROFILE: "{{ .Values.keycloak.defaultprofile }}"
    {{- else }}
    KEYCLOAK_MODE: ""
    {{- end }}
    {{- if .Values.usage_system.enabled }}
    USAGE_SERVICE_HOST: "{{ .Values.usage_system.host }}"
    USAGE_SERVICE_PORT: "{{ .Values.usage_system.port }}"
    USAGE_SERVICE_TLS: "{{ .Values.usage_system.tls }}"
    {{- end }}
