apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-ui
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: ui
data:
    # SSL_CERT_PATH: /etc/ssl/nginx/nginx.crt
    # SSL_KEY_PATH: /etc/ssl/nginx/nginx.key
    API_HOST: {{ include "sfapm.fullname" . }}-server
    API_PORT: "{{ .Values.sfapm.service.port }}"