apiVersion: v1
kind: Service
metadata:
  name: {{ include "sfapm.fullname" . }}
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: apm
spec:
  type: {{ .Values.sfapm.service.type }}
  ports:
    - port: {{ .Values.sfapm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sfapm.selectorLabels" . | nindent 4 }}
    app: sfapm
    role: apm
