apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfapm.fullname" . }}-celery-provision
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: celery
    queue: provision
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sfapm.selectorLabels" . | nindent 6 }}
      app: sfapm
      role: celery
      queue: provision
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sfapm.selectorLabels" . | nindent 8 }}
        app: sfapm
        role: celery
        queue: provision
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfapm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sfapm.image.repository }}:{{ .Values.sfapm.image.tag }}"
          imagePullPolicy: {{ .Values.sfapm.image.pullPolicy }}
          command: ["bash", "-c"]
          args: [{{ .Values.celery.provision.command }}]
          env:
          {{- range $key, $value := .Values.celery.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: DB_USER
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sfapm.fullname" . }}
                  key: REDIS_PORT 
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
