apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-apm
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: server
data:
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "snappyflow"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"
    VIZBUILDER_HOST: {{ include "sfapm.fullname" . }}-vizbuilder
    VIZBUILDER_PORT: "{{ .Values.vizbuilder.service.port }}"