apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-vizbuilder
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: vizbuilder
data:
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "vizbuilder"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"
    API_HOST: {{ include "sfapm.fullname" . }}-sfapm
    API_PORT: "{{ .Values.sfapm.service.port }}"
