apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfapm.fullname" . }}-vizbuilder
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: vizbuilder
spec:
  replicas: {{ .Values.sfapm.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfapm.selectorLabels" . | nindent 6 }}
      app: sfapm
      role: vizbuilder
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sfapm.selectorLabels" . | nindent 8 }}
        app: sfapm
        role: vizbuilder
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfapm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: migration
          image: "{{ .Values.vizbuilder.image.repository }}:{{ .Values.vizbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.vizbuilder.image.pullPolicy }}
          command: ["bash"]
          args: ["-c", "python manage.py makemigrations && python manage.py migrate"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-vizbuilder
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data 
      containers:
        - name: vizbuilder
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.vizbuilder.image.repository }}:{{ .Values.vizbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.vizbuilder.image.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-vizbuilder                                  
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # livenessProbe:
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   httpGet:
          #     path: /snappyflow/status
          #     port: http
          # readinessProbe:
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   httpGet:
          #     path: /snappyflow/status
          #     port: http
          resources:
            {{- toYaml .Values.vizbuilder.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
