kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "raw-query-exec-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "presto": {
        "user": "{{ .Values.presto.user }}",
        "catalog": "{{ .Values.presto.catalog }}",
        "schema": "{{ .Values.presto.schema }}"
      },
      "logArchivalURL": "http://{{ template "raw-query-exec-controller.log-archival.fullname" . }}"
    }
