apiVersion: v1
kind: Service
metadata:
  name: jaeger-port
  labels:
    app: jaeger-port
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 14268
    targetPort: 14268
    nodePort: 32268
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
