apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfnginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sfnginx.name" . }}
    helm.sh/chart: {{ include "sfnginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  snappyflow.conf: |
    server {
        listen 80;
        location /sfmetrics/ {
            proxy_pass {{ .Values.config.sfmetrics_endpoint }};
        }
        location /sftrace/ {
            proxy_pass {{ .Values.config.sftrace_endpoint }};
        }
        location / {
            add_header Content-Type text/plain;
            return 200;
        }
        # redirect server error pages to the static page /40x.html
        #
        error_page 404 /404.html;
            location = /40x.html {
        }
        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

