apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sinks-monitor
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ingest-controller.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedules.sink | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            release: {{ .Release.Name }}
        spec:
          containers:
          - name: main
            image: snappyflowml/sink-monitor-consumer-groups:2
            imagePullPolicy: Always
            command: ["bash"]
            args: ["-c", "python app.py connect-s3"]
            volumeMounts:
              - name: {{ template "log-archival.fullname" . }}
                mountPath: "/etc/config"
          restartPolicy: Never
          volumes:
            - name: {{ template "log-archival.fullname" . }}
              configMap:
                name: {{ template "log-archival.fullname" . }}

