kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "dataset-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "ingestControllerURL": "http://{{ template "dataset-controller.ingest-controller.fullname" . }}",
      "rawQueryExecControllerURL": "http://{{ template "dataset-controller.raw-query-exec-controller.fullname" . }}",
      "logArchivalURL": "http://{{ template "dataset-controller.log-archival.fullname" . }}",
      "billingURL": "{{ index .Values "billing-service" "scheme" }}://{{ index .Values "billing-service" "url" }}",
      "rawDataCleanupDays": {{ .Values.rawDataCleanupDays}},
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "dataset-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "serverPort": "{{ .Values.serverPort }}"
    }
