apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "dataset-controller.fullname" . }}-enforce-policy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-controller.labels" . | indent 4 }}
spec:
  schedule: "1 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: policy-enforce
            image: snappyflowml/busybox-curl:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -X POST {{ include "dataset-controller.fullname" . }}/datasets/policy/enforce
          restartPolicy: OnFailure

