# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
customMetrics:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 150Mi

archivalConnectAutoscaling:
  enabled: true
  cpu:
    targetAverageValue: 680m # 85% of CPU limit allocated to connector
  memory:
    targetAverageValue: 1536 # MiB -> When memory utilization reaches x Mib, auto-scaling kicks in. Value should be ~75% of kafka-connect connector container memory limit

apmConnectAutoscaling:
  enabled: true
  cpu:
    targetAverageValue: 435m # 85% of CPU limit allocated to connector
  memory:
    targetAverageValue: 1920 # MiB -> When memory utilization reaches x Mib, auto-scaling kicks in. Value should be ~75% of kafka-connect connector container memory limit

restKafkaAutoscaling:
  enabled: true
  cpu:
    targetAverageValue: 450m # 90% of CPU limit allocated to rest-server
  memory:
    targetAverageValue: 762 # MiB -> When memory utilization reaches x Mib, auto-scaling kicks in. Value should be ~85% of kafka-connect connector container memory limit
