{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-rest-prometheus.yml: |+
    startDelaySeconds: 120
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
    - "java.lang:*"
    - "java.nio:*"
    - "kafka.rest:type=jersey-metrics,*"
    - "kafka.rest:type=jetty-metrics,*"
    - "org.eclipse.jetty.util.thread:*"
    rules:
    - pattern: "kafka.rest<type=jersey-metrics><>(.+?)\\.(.+)\\+v2\\.([^\\.]+)\\:"
      cache: true
      name: kafka_rest_api_$3
      labels:
        api-version: "v2"
        api-group: "$1"
        api: "$2"
    - pattern: "kafka.rest<type=jersey-metrics><>v3\\.([^\\.]+)\\.(.+?)\\.([^\\.]+)\\:"
      cache: true
      name: kafka_rest_api_$3
      labels:
        api-version: "v3"
        api-group: "$1"
        api: "$2"
    - pattern: "kafka.rest<type=jersey-metrics, http_status_code=(.+)><>(.+?)\\.(.+)\\+v2\\.([^\\.]+)\\:"
      cache: true
      name: kafka_rest_api_$4
      labels:
        api-version: "v2"
        api-group: "$2"
        api: "$3"
        status-code: "$1"
    - pattern: "kafka.rest<type=jersey-metrics, http_status_code=(.+)><>v3\\.([^\\.]+)\\.(.+?)\\.([^\\.]+)\\:"
      cache: true
      name: kafka_rest_api_$4
      labels:
        api-version: "v3"
        api-group: "$2"
        api: "$3"
        status-code: "$1"
    - pattern: kafka.rest<type=jersey-metrics>
      cache: true
    - pattern: kafka.rest<type=jetty-metrics>
      cache: true
    - pattern: org.eclipse.jetty.util.thread<type=(.+), id=(.+)><>([^:]+)
      cache: true
      name: kafka_rest_jetty_$1_$3
      labels:
        id: "$2"
    - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
      name: java_lang_$1_$4_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><(.+)>(\w+)
      name: java_lang_$2_$4_$3_$1
      cache: true
    - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
      name: java_lang_$1_$3_$2
      cache: true
    - pattern: java.lang<name=(.+), type=(.+)><>(\w+)
      name: java_lang_$2_$3_$1
      cache: true
    - pattern: java.lang<type=(.*)>
      cache: true
    - pattern: java.nio<type=(.+), name=(.+)><>(\w+)
      name: java_nio_$1_$3_$2
{{- end }}
