{{- if .Values.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name: {{ template "sf-apm-agents.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sf-apm-agents.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "sf-apm-agents.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
