{{- if .Values.cluster_monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sf-apm-agents.cluster.fullname" . }}
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "sf-apm-agents.name" . }}-cluster
        image: "{{ .Values.cluster_monitoring.image.repository }}:{{ .Values.cluster_monitoring.image.tag }}"
        imagePullPolicy: {{ .Values.cluster_monitoring.image.pullPolicy }}
        resources:
{{ toYaml .Values.cluster_monitoring.resources | indent 12 }}
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
          {{- if .Values.application_monitoring.enabled }}
          - name: appconfig
            mountPath: /opt/appconfig
            readOnly: true
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sf-apm-agents.cluster.fullname" . }}
        {{- if .Values.application_monitoring.enabled }}
        - name: appconfig
          configMap:
            name: {{ template "sf-apm-agents.application.fullname" . }}
        {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
{{- if .Values.cluster_monitoring.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cluster_monitoring.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
