{{- if .Values.cluster_monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sf-apm-agents.cluster.fullname" . }}
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
data:
  config.yaml: |
{{- if .Values.cluster_monitoring.configmap }}
{{ toYaml .Values.cluster_monitoring.configmap | indent 4 }}
{{- end }}
{{- if .Values.config }}
{{ toYaml .Values.config | indent 4 }}
{{- end }}
{{- end }}
