apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-logging
  labels:
    app: {{ template "sf-apm-agents.fullname" . }}-logging
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.fullname" . }}-logging
      release: {{ .Release.Name }}
      role: logging
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.fullname" . }}-logging
        release: {{ .Release.Name }}
        role: logging
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      initContainers:
      - name: config
        image: "{{ .Values.fluentds.image.config.repository }}:{{ .Values.fluentds.image.config.tag }}"
        imagePullPolicy: "{{ .Values.fluentds.image.pullPolicy }}"
        volumeMounts:
          - name: config-apm
            mountPath: /opt/config
          - name: config
            mountPath: /etc/td-agent-bit
      containers:
      - name: fluent-bit
        image: "{{ .Values.fluentds.image.fluent_bit.repository }}:{{ .Values.fluentds.image.fluent_bit.tag }}"
        imagePullPolicy: "{{ .Values.fluentds.image.pullPolicy }}"
        command:
         - source
         - "/etc/config-gen/env"
         - cp
         - "/etc/config-gen/env/output.conf"
         - "/etc/td-agent-bit/output.conf"
         - "/fluent-bit/bin/fluent-bit"
         - "-c"
         - "/etc/td-agent-bit/fluent-bit.conf"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: config
            mountPath: /etc/config-gen
      terminationGracePeriodSeconds: 30
    {{- if .Values.fluentds.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentds.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.fluentds.tolerations }}
      tolerations:
{{ toYaml .Values.fluentds.tolerations | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-apm
          configMap:
            name: "{{ template "sf-apm-agents.application.fullname" . }}"
