{{- if .Values.fluentbit.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-logging
  labels:
    app: {{ template "sf-apm-agents.fullname" . }}-logging
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.fullname" . }}-logging
      release: {{ .Release.Name }}
      role: logging
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.fullname" . }}-logging
        release: {{ .Release.Name }}
        role: logging
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      initContainers:
      - name: config
        image: "{{ .Values.fluentbit.image.config.repository }}:{{ .Values.fluentbit.image.config.tag }}"
        imagePullPolicy: "{{ .Values.fluentbit.image.pullPolicy }}"
        volumeMounts:
          - name: config-apm
            mountPath: /opt/config
          - name: config
            mountPath: /etc/td-agent-bit
      containers:
      - name: fluent-bit
        image: "{{ .Values.fluentbit.image.fluent_bit.repository }}:{{ .Values.fluentbit.image.fluent_bit.tag }}"
        imagePullPolicy: "{{ .Values.fluentbit.image.pullPolicy }}"
        command: ["/bin/bash","-c"]
        args: ["source /etc/config-gen/env && cp -f /etc/config-gen/output.conf /etc/td-agent-bit/output.conf && cd /etc/td-agent-bit/ && /fluent-bit/bin/fluent-bit -c /etc/td-agent-bit/fluent-bit.conf"]
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: config
            mountPath: /etc/config-gen
      terminationGracePeriodSeconds: 30
    {{- if .Values.fluentbit.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentbit.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.fluentbit.tolerations }}
      tolerations:
{{ toYaml .Values.fluentbit.tolerations | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-apm
          configMap:
            name: "{{ template "sf-apm-agents.application.fullname" . }}"
{{- end }}
