apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sf-apm-agents.heartbeat.fullname" . }}
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "sf-apm-agents.name" . }}-heartbeat
        image: "{{ .Values.heartbeat.image.repository }}:{{ .Values.heartbeat.image.tag }}"
        imagePullPolicy: {{ .Values.heartbeat.image.pullPolicy }}
        resources:
{{ toYaml .Values.heartbeat.resources | indent 12 }}
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "sf-apm-agents.heartbeat.fullname" . }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
{{- if .Values.heartbeat.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.heartbeat.nodeSelector | indent 8 }}
{{- end }}
