{{- if .Values.application_monitoring.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-storage
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.name" . }}
      release: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1      
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      hostPID: true
      containers:
        - name: volume-exporter
          image: "{{ .Values.application_monitoring.storage_monitoring.image.repository }}:{{ .Values.application_monitoring.storage_monitoring.image.tag }}"
          imagePullPolicy: {{ .Values.application_monitoring.storage_monitoring.image.pullPolicy }}
          resources:
{{ toYaml .Values.application_monitoring.storage_monitoring.resources | indent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
            capabilities:
              add:
              - SYS_ADMIN
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              mountPropagation: Bidirectional
            - name: sys
              mountPath: /host/sys
              mountPropagation: Bidirectional
            - name: root-fs
              mountPath: /rootfs
              mountPropagation: Bidirectional
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: clusterconfig
              mountPath: /etc/clusterconfig
              readOnly: true
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root-fs
          hostPath:
            path: /
        - name: config
          configMap:
            name: {{ template "sf-apm-agents.application.fullname" . }}
        - name: clusterconfig
          configMap:
            name: {{ template "sf-apm-agents.cluster.fullname" . }}
{{- end }}
