dependencies:
- name: nginx-ingress
  version: 3.6.3
  repository: file://./sub_charts/nginx-ingress
- name: cp-schema-registry
  version: 0.1.0
  repository: file://./sub_charts/cp-schema-registry
- name: cp-kafka-rest
  version: 0.1.0
  repository: file://./sub_charts/cp-kafka-rest
- name: s3-kafka-connect
  version: 0.1.0
  repository: file://./sub_charts/s3-kafka-connect
  condition: global.archival.enabled
- name: es-kafka-connect
  version: 0.1.0
  repository: file://./sub_charts/es-kafka-connect
- name: autoscaling
  version: 0.1.0
  repository: file://./sub_charts/autoscaling
- name: authenticator
  version: 0.1.0
  repository: file://./sub_charts/authenticator
- name: sfk-interface
  version: 0.1.0
  repository: file://./sub_charts/sfk-interface
- name: signatures
  version: 0.1.0
  repository: file://./sub_charts/signatures
- name: minio
  version: 8.0.10
  repository: file://./sub_charts/minio
  condition: global.secrets.gcs.enable
