apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}-haproxy-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: haproxy
data:
  haproxy.cfg: |
    global
      log         127.0.0.1 local2

      chroot      /var/lib/haproxy
      pidfile     /var/run/haproxy.pid
      maxconn     4000
      user        haproxy
      group       haproxy
    # daemon

    # turn on stats unix socket
      stats socket /var/lib/haproxy/stats


    defaults
      mode                    http
      log                     global
      option                  httplog
      option                  dontlognull
      option http-server-close
      option forwardfor       except 127.0.0.0/8
      option                  redispatch
      retries                 3
      timeout http-request    10s
      timeout queue           1m
      timeout connect         10s
      timeout client          1m
      timeout server          1m
      timeout http-keep-alive 10s
      timeout check           10s
      maxconn                 3000




    frontend stats
       bind *:26999
       option http-use-htx
       http-request use-service prometheus-exporter if { path /metrics }
       stats enable
       stats uri /stats
       stats refresh 10s
    frontend  main
      bind *:8080
      stats uri /haproxy?stats
      default_backend app
      capture request header User-Agent len 120




    backend app
      balance     roundrobin
      server  app1 {{ template "spring.fullname" . }}-app1:80
      server  app2 {{ template "spring.fullname" . }}-app2:80
      
        
