apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-sfagent
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}

data:
  config.yaml: |-
    key: "{{ .Values.global.key }}"
    metrics:
        plugins:
        - name: postgres
          enabled: true
          interval: 10
