apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cp-kafka.fullname" . }}-exporter
  labels:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    snappyflow/appname: sf-data-path
    snappyflow/projectname: on-premise
    role: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cp-kafka.fullname" . }}-exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cp-kafka.fullname" . }}-exporter
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "danielqsj/kafka-exporter:v1.0.1"
        name: kafka-exporter
        args:
          - --kafka.server=kafka-cp-kafka-headless:9092
          - --web.listen-address=:9308
        ports:
          - containerPort: 9308
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
