# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

  postgresql:
    host: ""
    postgresqlDatabase: new_archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  secrets:
    gcs:
      enable: false
      secret: XX
      key: XX.json
    aws:
      enable: true
      AWS_DEFAULT_REGION: us-west-2
      AWS_ACCESS_KEY_ID: XXXX
      AWS_SECRET_ACCESS_KEY: XXXX

  kafkaBrokers: ""

  snappyflowDatapath:
    enabled: true
    releaseName: sf-datapath

  hive:
    userName: ubuntu
    host: 127.0.0.1
    port: 10000
    auth: NONE

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: ""
  snappyflowAppName: ""

  imagePullSecrets:
  - name: xxxx

dataset-controller-cron:
  intervalInSec: 1800
  path: "/datasets/uncompact/refresh"
  dataset-controller:
    service:
      servicePort: 80

compaction-controller-create-cron:
  intervalInSec: 600
  path: "/compaction/create"
  compaction-controller:
    service:
      servicePort: 80

compaction-controller-queue-cron:
  intervalInSec: 600
  path: "/compaction/queue"
  compaction-controller:
    service:
      servicePort: 80

compaction-controller-start-cron:
  intervalInSec: 120
  path: "/compaction/start"
  compaction-controller:
    service:
      servicePort: 80

ingest-controller-sink-cron:
  intervalInSec: 300
  path: "/ingest/datasets/monitor/sink"
  ingest-controller:
    service:
      servicePort: 80

dataset-controller-billing-cron:
  intervalInSec: 3600
  path: "/datasets/profile/billing"
  dataset-controller:
    service:
      servicePort: 80

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  cron:
    limits:
      cpu: 25m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 25Mi
