apiVersion: v1
name: sfagent
version: 2.0.1
appVersion: "1.1"
description: Cluster and Application Monitoring system for Maplelabs' snappyFlow APM.
home: http://www.snappyflow.io
keywords:
- monitoring
- alerting
- metric
maintainers:
  - name: Upendra
    email: upendra.sahu@maplelabs.com
engine: gotpl

