rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if create is true, REQUIRED if create is false
  serviceAccountName: default

config:
  # unique cluster name to add in documents as _tag_cloudName
  cluster_name: kubernetes
  # project name label key, value of the label will be added in documents as _tag_projectName
  # projectname_label: snappyflow/projectname
  #
  # application name label key, value of the label will be added in documents as _tag_appName
  # appname_label: snappyflow/appname
  #
  # SnappyFlow APM Elasticsearch Target key copied from APM cloudprofile
  # This is used for application inventory documents, application heartbeats.
  key: ""
  #
  # SnappyFlow Key for cloud heartbeat and metrics, 
  # If not provided then key used
  # cloud_key: "cluster_key"
  
  # Heartbeat interval
  interval: 300
  

# Node Agent
# Per node Plugin Pod
#  container for prometheus poller
#  container for node/pod kubelet monitoring + storage metrics
#  container for fluent-bit logs
#  container for inventory heartbeat
node_agent:
  node_inventory:
    image:
      repository: snappyflowml/sfkube-node-inventory
      tag: latest
      pullPolicy: Always

    ## container resource requests and limits
    ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 256m
        memory: 256Mi

  node_metrics:
    image:
      repository: snappyflowml/sfkube-node-metrics
      tag: latest
      pullPolicy: Always
    # if enabled
    configmap:
      # cluster monitoring interval, default is 300 seconds
      interval: 300
      # Tags to be added in cluster metrics document
      #tags: {}
      #target: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 512Mi
  
  prometheus_poller:
    image:
      repository: snappyflowml/sfkube-node-prom
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    configmap:
      log_dir: /tmp
      interval: 30
    plugin_interval:
      elasticsearch:
        cluster: 300
        node: 300
        index: 900
      nginx:
        default: 300
      mysql:
        default: 300
      kafka:
        default: 300
      jmx:
        default: 300
      kafka-jmx:
        default: 300
      zookeeper-zmx:
        default: 300

  fluentbit:
    enabled: true
    drop_cluster_logs: false
    image:
      fluent_bit:
        repository: snappyflowml/fluentbit-sfapm
        tag: latest
      config:
        repository: snappyflowml/kube-fluent-init
        tag: latest
      pullPolicy: Always

    podAnnotations: {}

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 10m
      #   memory: 8Mi

  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: NoSchedule

  nodeSelector: {}

# cluster level plugin Pod
#   Container with cloud heartbeat + cluster document
#   Container for kube events
cluster_agent:
  # Cluster monitoring
  cluster_monitoring:
    image:
      repository: snappyflowml/sfkube-cluster
      tag: latest
      pullPolicy: Always
    # if enabled
    configmap:
      # cluster monitoring interval, default is 300 seconds
      interval: 300
      # Tags to be added in cluster metrics document
      #tags: {}
      #target: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 256Mi

  event_metrics:
    image:
      repository: snappyflowml/sfkube-events
      tag: latest
      pullPolicy: Always

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 512Mi

  tolerations: []

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}


