{{- if .Values.mysql.aws.enabled }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ include "spring.fullname" . }}-rds-binding
spec:
  instanceRef:
    name: {{ include "spring.fullname" . }}-rds
{{- end }}