kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-dataset-controller-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "dataset-controller-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.dataset-controller.fullname" . }}:{{ index .Values "dataset-controller-cron" "dataset-controller" "service" "servicePort"}}{{ index .Values "dataset-controller-cron" "path"}}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-compaction-controller-create-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "compaction-controller-create-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.compaction-controller.fullname" . }}:{{ index .Values "compaction-controller-create-cron" "compaction-controller" "service" "servicePort"}}{{ index .Values "compaction-controller-create-cron" "path"}}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-compaction-controller-queue-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "compaction-controller-queue-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.compaction-controller.fullname" . }}:{{ index .Values "compaction-controller-queue-cron" "compaction-controller" "service" "servicePort"}}{{ index .Values "compaction-controller-queue-cron" "path"}}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-compaction-controller-start-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "compaction-controller-start-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.compaction-controller.fullname" . }}:{{ index .Values "compaction-controller-start-cron" "compaction-controller" "service" "servicePort"}}{{ index .Values "compaction-controller-start-cron" "path"}}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-ingest-controller-sink-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "ingest-controller-sink-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.ingest-controller.fullname" . }}:{{ index .Values "ingest-controller-sink-cron" "ingest-controller" "service" "servicePort"}}{{ index .Values "ingest-controller-sink-cron" "path"}}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cron.fullname" . }}-dataset-controller-billing-cron
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "intervalInSec": {{ index .Values "dataset-controller-billing-cron" "intervalInSec" }},
      "url": "http://{{ include "cron.dataset-controller.fullname" . }}:{{ index .Values "dataset-controller-billing-cron" "dataset-controller" "service" "servicePort"}}{{ index .Values "dataset-controller-billing-cron" "path"}}"
    }
