{{ define "userlist.txt.1.0.0" }}
{{- range $k, $v := .Values.users }}
{{ $k | quote }} {{ $v | quote }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-userlist
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: |-
{{ include "userlist.txt.1.0.0" . | b64enc | indent 4 }}