# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
monitor:
  image:
    repository: snappyflowml/monitor
    tag: dev-6
    pullPolicy: IfNotPresent
  containerResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi

jobserver:
  image:
    repository: ahmed3465/jobserver
    tag: gcp-v1
    pullPolicy: Always
  serverPort: 5002
  service:
    servicePort: 5002
  sparkProperties:
    logDirectory: sparkhs/spark-hs
  containerResources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 50Mi

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
