# Default values for sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
monitor:
  image:
    repository: snappyflowml/monitor
    tag: 7
    pullPolicy: IfNotPresent
  containerResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi

jobserver:
  image:
    repository: snappyflowml/job-server
    tag: 11
    pullPolicy: IfNotPresent
  serverPort: 5002
  service:
    servicePort: 5002
  sparkProperties:
    logDirectory: sparkhs/spark-hs
  containerResources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 50Mi

compactionImage: snappyflowml/spark-compact-orc:1

nameOverride: ""

fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
