apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charging.fullname" . }}-config
  labels:
    {{- include "charging.labels" . | nindent 4 }}
data:
    {{- if .Values.postgresql.enabled }}
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "apmbilling"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    {{- else }}
    DB_HOST: {{ .Values.postgresql.external.dbHost }}
    DB_PORT: {{ .Values.postgresql.external.dbPort | default "5432"  | quote }}
    DB_NAME: "apmbilling"
    DB_USER: {{ .Values.postgresql.external.dbUser }}
    DB_PASSWORD: {{ .Values.postgresql.external.dbPassword }}
    {{- end }}
    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"
    HOURLY_DATA_RETAIN_DAYS: {{ .Values.hourly_data_retain_days | quote }}
