apiVersion: v1
kind: Service
metadata:
  name: {{ include "charging.fullname" . }}
  labels:
    {{- include "charging.labels" . | nindent 4 }}
    service: charging
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charging.selectorLabels" . | nindent 4 }}
    service: charging
