kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "query-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "datasetControllerURL": "http://{{ template "query-controller.dataset-controller.fullname" . }}",
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "query-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "hive": {
        "userName": "root",
        "host": "{{ template "query-controller.hive-server.fullname" . }}",
        "port": 10000,
        "auth": "NONE"
      },
      "ingestControllerURL": "http://{{ template "query-controller.ingest-controller.fullname" . }}",
      "jobTypes": ["LogQuery", "Histogram"],
      "logArchivalURL": "http://{{ template "query-controller.log-archival.fullname" . }}",
      "prestoPython": "{{ .Values.prestoPython }}",
      "prestoPythonScript": "{{ .Values.prestoPythonScript }}",
      "serverPort": "{{ .Values.serverPort }}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "query-controller.fullname" . }}-execution-controller
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "query-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "presto": {
        "user": "{{ .Values.prestoUser }}",
        "catalog": "{{ .Values.prestoCatalog }}",
        "schema": "{{ .Values.prestoSchema }}"
      },
      "logArchivalURL": "http://{{ template "query-controller.log-archival.fullname" . }}",
      "interval": {{ .Values.monitorInterval }}
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "query-controller.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "cleanIntervalInHour": {{ .Values.cleanIntervalInHour }},
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "query-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "queryControllerURL": "http://{{ template "query-controller.fullname" . }}"
    }
