# Default values for sfk-interface.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

  postgresql:
    host: "archival-dev.cmebsmm3knzu.us-west-2.rds.amazonaws.com"
    postgresqlDatabase: archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  kafkaBrokers: ""

  archival:
    enabled: true
    releaseName: archival

  sfAgentInput:
    host: 127.0.0.1
    port: 443
    scheme: https

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "Kafka"
  snappyflowAppName: "ConsumersAndProducers"

  imagePullSecrets:
  - name: xxxx

replicaCount: 1

image:
  repository: snappyflowml/sfk-interface
  pullPolicy: IfNotPresent
  tag: 0.0.6

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  port: 8080

external:
  enabled: false
  type: NodePort
  externalTrafficPolicy: Cluster

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  interface:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

cron:
  intervalInSec: 300
  path: "/monitor"

  containerResources:
    limits:
      cpu: 25m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 25Mi
