apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-sfagent-zookeeper
  labels:
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    logging:
      plugins:
      - name: zookeeper-general
        enabled: true
        config:
          log_level:
            - error
            - info
            - warn
            - debug
            - notice
          log_path: /var/log/zookeeper/server.log 
    metrics:
      plugins:
      - name: zookeeperjmx
        enabled: true
        interval: 300
        config:
          documentsTypes:
            - jmxStats
            - zookeeperStats
          jolokiaPort: 8778
          RMIPort: 8778
          jolokiaContext: jolokia
          jolokiaProtocol: http
          jolokiaProxy: false
