# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

  postgresql:
    host: ""
    postgresqlDatabase: new_archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  secrets:
    gcs:
      enable: false
      secret: XX
      key: XX.json
    aws:
      enable: true
      AWS_DEFAULT_REGION: us-west-2
      AWS_ACCESS_KEY_ID: XXXX
      AWS_SECRET_ACCESS_KEY: XXXX

  kafkaBrokers: ""

  snappyflowDatapath:
    enabled: true
    releaseName: sf-datapath

  hive:
    userName: ubuntu
    host: 127.0.0.1
    port: 10000
    auth: NONE

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: ""
  snappyflowAppName: ""

  imagePullSecrets:
  - name: xxxx

image:
  repository: snappyflowml/ingest-controller
  tag: 0.0.10
  pullPolicy: IfNotPresent

schemaCreate:
  image:
    repository: snappyflowml/create-schemas
    tag: 0.0.8
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serverPort: ":5000"

service:
  servicePort: 5000

external:
  enabled: false
  type: NodePort
  externalTrafficPolicy: Cluster

nodeSelector: {}

tolerations: []

affinity: {}

dataset-controller:
  service:
    servicePort: 5001

spark-manager:
  jobserver:
    service:
      servicePort: 5002

log-archival:
  service:
    servicePort: 5003

containerResources:
  ingestcontroller:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
  schemacreate:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
