kind: Service
apiVersion: v1
metadata:
  name: {{ template "elasticsearch.uname" . }}-exporter
  labels:
    app: {{ template "elasticsearch.uname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "elasticsearch.uname" . }}
    role: exporter
    snappyflow/plugin: elasticsearch
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if .Values.exporter.service.annotations }}
  annotations:
{{ toYaml .Values.exporter.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - name: exporter
      port: {{ .Values.exporter.service.httpPort }}
      protocol: TCP
  selector:
    component: {{ template "elasticsearch.uname" . }}
    role: exporter
