# Default values for Ingest Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

  postgresql:
    host: "archival-dev.cmebsmm3knzu.us-west-2.rds.amazonaws.com"
    postgresqlDatabase: archival
    postgresqlUsername: archive
    postgresqlPassword: archive123
    servicePort: 5432

  kafkaBrokers: ""

  archival:
    enabled: true
    releaseName: archival

  sfAgentInput:
    host: 127.0.0.1
    port: 443
    scheme: https

  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "Kafka"
  snappyflowAppName: "ConsumersAndProducers"

  imagePullSecrets:
  - name: xxxx

image:
  repository: snappyflowml/signatures
  tag: 0.0.11
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  servicePort: 8888

nodeSelector: {}

tolerations: []

affinity: {}

containerResources:
  signatures:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
