replicaCount: 1

image:
  repository: snappyflowml/raw-query-exec-controller
  pullPolicy: IfNotPresent
  tag: "dev-1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 10Mi

nodeSelector: {}

tolerations: []

affinity: {}

presto:
  catalog: hive
  schema: default
  user: maplelabs
