kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-manager.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
data:
  monitor-config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "spark-manager.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "nameSpace": "{{ .Release.Namespace }}"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-manager.fullname" . }}-jobserver
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name":  "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user":  "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "compaction-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }}
      },
      "serverPort": ":{{ .Values.jobserver.serverPort }}",
      "propertiesFile": "/etc/spark-conf/spark-properties",
      "sparkSubmitPath": "/opt/spark-3.1.1-bin-hadoop2.7/bin/spark-submit"
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-manager.fullname" . }}-spark-properties
  namespace: {{ .Release.Namespace }}
data:
  spark-properties: |-
    spark.kubernetes.driver.limit.cores 1
    spark.kubernetes.executor.limit.cores 1
    spark.executor.instances 2
    spark.kubernetes.executor.request.cores 0.2
    spark.kubernetes.driver.request.cores 0.2
    spark.executor.memory 512m
    spark.driver.memory 512m
    spark.eventLog.enabled true
    spark.eventLog.dir s3a://{{ index .Values "jobserver" "sparkProperties" "logDirectory" }}
    spark.kubernetes.driver.label.{{ .Values.global.snappyflowProjectLabel}} {{ .Values.global.snappyflowProjectName }}
    spark.kubernetes.executor.label.{{ .Values.global.snappyflowProjectLabel}} {{ .Values.global.snappyflowProjectName }}
    spark.kubernetes.driver.label.{{ .Values.global.snappyflowAppLabel }} {{ .Values.global.snappyflowAppName }}
    spark.kubernetes.executor.label.{{ .Values.global.snappyflowAppLabel }} {{ .Values.global.snappyflowAppName }}
    spark.kubernetes.driver.label.release {{ .Release.Name }}
    spark.kubernetes.executor.label.release {{ .Release.Name }}
    spark.kubernetes.container.image snappyflowml/spark-compact-aws:3.0.1-0.0.1
    spark.kubernetes.driver.secretKeyRef.AWS_ACCESS_KEY_ID {{ .Release.Name }}-aws-secret:key
    spark.kubernetes.driver.secretKeyRef.AWS_SECRET_ACCESS_KEY {{ .Release.Name }}-aws-secret:secret
    spark.kubernetes.executor.secretKeyRef.AWS_ACCESS_KEY_ID {{ .Release.Name }}-aws-secret:key
    spark.kubernetes.executor.secretKeyRef.AWS_SECRET_ACCESS_KEY {{ .Release.Name }}-aws-secret:secret
    spark.kubernetes.namespace {{ .Release.Namespace }}
