name: Lint and Test Charts

on:
  push:
    branches:
      - 'master'
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: .github/ct.yaml
